### ISSUE TITLE
When merging words, it should auto keep the one with the most work done, meanings etc.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#104]

**Comment by postpostscript** [comment]
Am I correct in thinking that is is on the API side of things?

**Comment by HamptonMakes** [comment]
Not sure how this would work...?

**Comment by HamptonMakes** [comment]
Like, merging is to add one to another, so... we have to keep the edit screen showing the one you are on. It's hard to know "most work done" automatically in the interface. It would be weird if you added a synonym and then all the definitions on your edit screen changed.

**Comment by interestinall** [comment]
maybe not "most work done," but more defs maybe. For example, if the US
spelling has three defs and good examples and someone merges it into a UK
spelling, we lose the three defs and good examples. Yes you can see in the
proposal that that stuff is going to be cut, but it might be good to have a
failsafe in place.
