### ISSUE TITLE
Alerts tab messaging casts new users in negative light

### ISSUE THREAD

**Issue by OddBloke** [wordset/wordset#109]
A new user joined the site, and went through a bunch of open proposals, voting reasonably up and down on them. When I examined my alerts tab (not knowing at the time that it showed only nay votes), my initial reaction was that this new user had joined the site and just voted all my proposals down.

This made me feel negatively towards that user, until I realised what I was being shown. This is not conducive to community building.

**Comment by OddBloke** [comment]
As I understand it, only negative votes are displayed in order to make it clear that one of your proposals might be in jeopardy. However, in this case, they were all -1 votes, so didn't have a great deal of impact on my proposals.

Better would probably be to have "<proposed word> has some negative votes".

**Comment by HamptonMakes** [comment]
This is different on the new design!
