### ISSUE TITLE
HTTP and HTTPS don't share session information

### ISSUE THREAD

**Issue by OddBloke** [wordset/wordset#110]
Could also be: "HTTP doesn't just redirect straight to HTTPS" :grin:

**Comment by HamptonMakes** [comment]
Oh, that's annoying... :/

**Comment by HamptonMakes** [comment]
We had to disable https redirection, in order to get prerendering working for Google-bot and the like.

**Comment by HamptonMakes** [comment]
In 3.0 they will.
