### ISSUE TITLE
No option to create a word when it's a prefix of an existing word

### ISSUE THREAD

**Issue by OddBloke** [wordset/wordset#112]
I was looking to see if 'roti' existed in the dictionary; it did not, but I wasn't presented with the option to create it because 'rotifier' and 'rotisserie' _are_ in the dictionary.

Ideally, if the exact string typed in doesn't exist in the dictionary, the last option in the drop-down should be the 'add word' link.

**Comment by interestinall** [comment]
Good catch!

In the meantime, you can go to https://www.wordset.org/words/en/new and add things there. Or just typing gibberish will also launch the "add word" link.

**Comment by malrase** [comment]
This is now live!

Also, I believe in the new design there will be an ability to go to the "create new word" page directly from the homepage.
