### ISSUE TITLE
Chat requires a hard refresh now and again.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#113]

**Comment by interestinall** [comment]
Otherwise messages are missed.

**Comment by HamptonMakes** [comment]
it stops working or just the times being off?

what happens exactly?

**Comment by interestinall** [comment]
Sometimes there are gaps in my chat history which are suddenly filled in when I hard refresh.

**Comment by HamptonMakes** [comment]
gotcha.

I'm guessing that's when your computer is asleep... maybe we have to do some timer-based refresh.
