### ISSUE TITLE
When searching for a word, pressing the go button doesn't redirect you to the word (when typing)

### ISSUE THREAD

**Issue by ghost** [wordset/wordset#115]

**Comment by interestinall** [comment]
I am assuming this is iOS related. If not, let me know :)

**Comment by ghost** [comment]
It is. How do you add labels to an issue?

**Comment by interestinall** [comment]
If you are on git, there is a labels link with a gear next to it on the right hand side. If you are on waffle, it is on the bottom.

**Comment by ghost** [comment]
Hmmm; I don't see it :(

**Comment by interestinall** [comment]
which one are you using?

**Comment by ghost** [comment]
GitHub

**Comment by interestinall** [comment]
<img width="1120" alt="screen shot 2015-09-24 at 14 59 40" src="https://cloud.githubusercontent.com/assets/4720348/10085164/1fd264d8-62cd-11e5-8558-9ac7153e1323.png">

**Comment by interestinall** [comment]
the word "Labels" doesn't really look clickable, but it is.

**Comment by ghost** [comment]
The gear isn't visible nor can I click on the word labels. I wonder if I don't have permissions...

**Comment by interestinall** [comment]
Hmm that could be! I thought we may be looking at different things. Until we get to the bottom of this, you can just write iOS somewhere in the description and I'll add the label :)

**Comment by ghost** [comment]
Ok. Thanks for all of the help!

**Comment by interestinall** [comment]
No worries!

**Comment by rakeshak** [comment]
To be specific, the Go button shall select the topmost word IF the topmost word is exactly equal to the word typed by the user; That's what a user would expect. We can go a step ahead and make the Go button select any topmost word (for example, a user wants to see the meaning of 'breakable'; he has to type till the word appears at the top –'breaka'– and tap Go). For this to work we should visually indicate that the topmost word is the one that would be selected if a user taps Go.

**Comment by rajkumariosdev** [comment]
When we search I am making the top most cell to have light gray background to visually indicate it will be selected. Let me know if you want me to do anything else. 
Now clicking Go, will load the first item.

**Comment by HamptonMakes** [comment]
I wasn't a fan of the grey background, so removed that... now it's just a list.
