### ISSUE TITLE
The history links should be more obviously clickable.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#117]

**Comment by HamptonMakes** [comment]
like...?

**Comment by interestinall** [comment]
<img width="557" alt="screen shot 2015-09-25 at 17 17 27" src="https://cloud.githubusercontent.com/assets/4720348/10113382/5f9a73e4-63a9-11e5-89c2-c5a14b320217.png">

I think it would be good if we had a darker color separating the history entries, for example, and a hover over change for each. That way each entry looks more individual and interactive.

What do you think?

**Comment by malrase** [comment]
This is, I suppose, more attn: @rakeshak . Something to keep in mind when designing the history page (e.g. here: http://www.wordset.org/en/test/proposals)

**Comment by rakeshak** [comment]
Yes, this is part of the redesign.

**Comment by interestinall** [comment]
fixed
