### ISSUE TITLE
iOS - word should be fixed to the top

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#118]
I think it would be better if the word / at least one spelling was fixed to the top and the defs slid under when scrolling down.

Right now it seems as if the word "exits" the header going up and the defs roll over a header that we can't see.

**Comment by HamptonMakes** [comment]
Not sure about the design implications of this...

**Comment by malrase** [comment]
Yeah, I'm not sure there's enough real estate on the phone. Even my 6S has only a couple of definitions with the headword.

**Comment by HamptonMakes** [comment]
I agree with michael... you can scroll back up if you want... :P
