### ISSUE TITLE
When the word a user is looking up is not in the dictionary, we should explain to them in a short message that wordset is a collaborative venture and link to the add word page.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#120]

**Comment by HamptonMakes** [comment]
I think we have this, right? Or something along these lines?

**Comment by malrase** [comment]
This is for the app, though.

**Comment by interestinall** [comment]
right for the app. as far as i can tell, if the word doesn't exist and you hit go nothing happens at all.

**Comment by HamptonMakes** [comment]
ooooohhhhhhh... hmmm... interesting... there are almost no cases (once we get metaphone in) that this will happen. You can pretty much type anything, and we'll find something.

**Comment by HamptonMakes** [comment]
So one of the issues here is that we use sounds-alike. So if you've typed "Sihk" (as my brother did), we will show "sick", etc. It's hard to show a list of legit results and kind of pretend like maybe you didn't mean to mistype?
