### ISSUE TITLE
WKWebView

### ISSUE THREAD

**Issue by HamptonMakes** [wordset/wordset#127]
For iOS8+, the DetailViewController should use WKWebView, this should maybe help with the audio issues.

**Comment by srkrambo** [comment]
The deployment target is 8.3, So we need to replace UIWebView with WKWebView right?

**Comment by HamptonMakes** [comment]
Oh, good point! Yeah, just replace it.

**Comment by srkrambo** [comment]
Updated to WKWebview. But the audio is not playing. Its on features/raj/issue-127 branch. 
Trying to figure this out. If any of have any comments/ suggestions. Please tell.

**Comment by HamptonMakes** [comment]
Well, the goal is also to replace the JS audio stuff.... The original version of the app compiled in a real OGG library for decoding and did some stuff to integrate with the audio framework. I even have access to the old code if that would help solve it.

Michael and I tried all the prepackaged OGG audio libraries we could, and ended up only being able to get the JS port to work.

—

**Comment by srkrambo** [comment]
This is done. Now the app uses WKWebview.
