### ISSUE TITLE
wordset://lookup/lang/word

### ISSUE THREAD

**Issue by HamptonMakes** [wordset/wordset#131]
When we encounter a URL in this format, we should open it.

wordset://lookup/en/word

"lookup" is fixed
"en" is the language (only one right now, but wordsetDB.langs must include it)
"word" is the word we are searching for, URI-escaped

Going to this should open the app to the word's DetailViewController

**Comment by donaldp24** [comment]
Ok, we can use handleOpenURL delegate of AppDelegate class...

**Comment by srkrambo** [comment]
This is done.
