### ISSUE TITLE
Should have a splash screen instead of a list of words

### ISSUE THREAD

**Issue by malrase** [wordset/wordset#132]
A number of users have said that seeing a list of words on launch of the app is a little disorientating.

We should have a splash screen instead, with a faint version of the logo.

**Comment by malrase** [comment]
![blank_home_screen](https://cloud.githubusercontent.com/assets/108884/10205053/ed0966d6-6773-11e5-800e-2327c3d91d51.jpg)

See this suggestion from rakesh.

**Comment by HamptonMakes** [comment]
The only thing that needs to happen with this now is showing the logo ghosted in the background. We already hide the list... so the left hand side is not representative.

It should look like the left hand one, but with the keyboard active.

**Comment by HamptonMakes** [comment]
I'm moving this to 7.1... I'm not happy with the wordset/wordset-ios#132 design... and the mockup above is lacking something. It's blank until we figure something else out.
