### ISSUE TITLE
CoreSpotlight Integration

### ISSUE THREAD

**Issue by HamptonMakes** [wordset/wordset#135]
We should integrate with the new core search features.

Most likely as a step after installing a new version... go through every word and register it with the internal search engine.

**Comment by donaldp24** [comment]
Guess, Core Search means using CoreData?

**Comment by srkrambo** [comment]
This is done and currently part of features/raj/SpotLightSearch branch. 
The API call self.api.seq(lang, text: seqText) in Wordset.swift was increasing the memory load heavily. So, I have added a boolean that disables the api call at the time of indexing.
After this I able to index all the words and but still the memory do increase to a certain level around 180MB on simulator. Let me know if it is possible to fetch title, description and keywords in a better way. Currently, I am fetching similar to master view controller, fetch 500 words, then I am looping through each to get its corresponding keywords and content description as used in detail view controller html.

**Comment by HamptonMakes** [comment]
Oh yeah, definitely don't want those API calls going! Nope, nope, nope! :)

Can you send a screenshot of the search results?

**Comment by srkrambo** [comment]
![simulator screen shot 19-oct-2015 5 01 02 am](https://cloud.githubusercontent.com/assets/3715771/10567328/913b5dd2-761e-11e5-88e8-94d4d6053c21.png)
