### ISSUE TITLE
App not choosing the matching seq with shortest amount of characters

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#138]
![img_0045](https://cloud.githubusercontent.com/assets/4720348/10340184/8a9ede0c-6cd4-11e5-8647-f33161a48a1a.jpg)

When you hit go here, it chooses Hitchens's Razor.

**Comment by interestinall** [comment]
This seems to have to do with the search algorithm considering "H" as coming before "h."

**Comment by HamptonMakes** [comment]
![image](https://cloud.githubusercontent.com/assets/111/10348137/414a2bea-6cec-11e5-981e-cd38b6f0e9b9.png)

**Comment by HamptonMakes** [comment]
yeah, what you had was wrong.

we've changed over to alphabetical, non-case-sensitive, so the above shows what it looks like now.
