### ISSUE TITLE
Add 'powered by Wordset' to iOS home screen

### ISSUE THREAD

**Issue by rakeshak** [wordset/wordset#144]
'Powered by Wordset' to be added to the home screen at the top left of the keyboard. 

Spec for 'Powered by':
font: Crimson-italic; 
font-size: 16pt;
color: #aaa;

This element should be 20pt above the top edge of the keyboard.

![iphone home](https://cloud.githubusercontent.com/assets/14918841/10359407/fd437b3e-6db5-11e5-9b50-d8c3715c90dc.png)
![ipad home](https://cloud.githubusercontent.com/assets/14918841/10359409/00e94782-6db6-11e5-84d9-4f3bdf04b900.png)

**Comment by srkrambo** [comment]
This is done.
