### ISSUE TITLE
after users search for a word, when they hit the search icon they merely go back.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#146]
I think this should create a new "clean" search, with the logo. Especially as we have a "back" icon as well.

**Comment by malrase** [comment]
Yeah, the search icon is a little strange right now. It's more of a stop-gap until we can get search on every page

**Comment by HamptonMakes** [comment]
Well, technically, it's a "go back all the way" link, as requested by @rakeshak. Eventually having on-detail-view-searching is a goal, but not for 7.x.  But, I definitely agree with your suggestion.

**Comment by rakeshak** [comment]
When I go back to the home screen by tapping the search icon the word I typed earlier is still there in the search bar. To perform a new search I have to delete that word, which is more work for me. The search bar should be empty.

**Comment by srkrambo** [comment]
It was already going all the way back to master view. Now I additionally clear the search textfield as mentioned above by Rakesh.
