### ISSUE TITLE
When smaller phone is rotated when searching, search bar is covered

### ISSUE THREAD

**Issue by malrase** [wordset/wordset#148]
In particular, the iPhone 6 (not the plus, which has a split view) –
![screen shot 2015-10-12 at 11 38 06a m](https://cloud.githubusercontent.com/assets/108884/10435580/ba78be4a-70d5-11e5-9167-a539e5f6db66.png)
Rotating back to portrait:
![screen shot 2015-10-12 at 11 39 15a m](https://cloud.githubusercontent.com/assets/108884/10435609/e35d9d44-70d5-11e5-9713-9fd84accebfa.png)
You can see the search bar is hidden.

**Comment by srkrambo** [comment]
Fixed
