### ISSUE TITLE
Issue with "Easy" word 

### ISSUE THREAD

**Issue by srkrambo** [wordset/wordset#149]
![simulator screen shot 14-oct-2015 11 38 29 am](https://cloud.githubusercontent.com/assets/3715771/10476081/44698a2e-7268-11e5-8842-53e88cdd26b2.png)

**Comment by rakeshak** [comment]
For me it appeared unstyled for a split second and then got styled. I encountered the same behavior with another word yesterday (I don't remember the word).

**Comment by HamptonMakes** [comment]
weiiiiird.

**Comment by srkrambo** [comment]
Its seems to be an issue only on iOS 8.4 and iOS 9.0, trying to figure out why.

**Comment by srkrambo** [comment]
Fixed it was issue caused by hyphen symbol (–)
