### ISSUE TITLE
community project page reload should bring the user back to the top of the page

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#152]
right now the new page loads, but it is not clear to the user that anything has happened until they scroll up.

**Comment by malrase** [comment]
Which page in particular?
http://www.wordset.org/projects?
Or a specific project?

**Comment by interestinall** [comment]
The individual word fix page in the project. When you make a project proposal it automatically loads another word that needs to be fixed, but it is unclear because the user is still looking at the submit button.

**Comment by malrase** [comment]
Gotcha!

**Comment by malrase** [comment]
This is not a valid bug in the new version.
