### ISSUE TITLE
iPad: Tapping any synonym and tapping back crashes the app

### ISSUE THREAD

**Issue by rakeshak** [wordset/wordset#160]

**Comment by rajkumariosdev** [comment]
Unable to replicate this. Is this specific to any device/ word?

**Comment by rakeshak** [comment]
It happens only in iPad. Mine is iPad 3rd generation running iOS 9.

**Comment by srkrambo** [comment]
Was able to replicate on iPad, will fix this tomorrow.

**Comment by srkrambo** [comment]
Fixed.
