### ISSUE TITLE
New feature: Settings

### ISSUE THREAD

**Issue by rakeshak** [wordset/wordset#162]
**How**: Settings screen shall be activated in two ways:
1. by tapping the settings icon at the top right.
2. by swiping from the right edge of the screen.

**Spec**: Here's a crude prototype of the settings screen https://www.dropbox.com/s/i602ghob804iurn/UI%20Prototype%202015-10-29.zip?dl=0 Spec for the animation, layout, dimensions, fonts, etc., can be found in the style.css file. 

**A note on gestures:** 
There shall be a total of 3 gestures for navigation.
1. Swipe left to right anywhere on the definitions area to go back to a previous word
2. Swipe right to left anywhere on the definitions area to go forward to the next word
3. Swipe from the right edge to left anywhere on the screen to show settings (the settings overlay should move along with the finger and should go to its fully visible position once you release your finger; just like how the Notification Center behave when swiped from the top edge of the screen in iOS.

![definitions screen with settings icon](https://cloud.githubusercontent.com/assets/14918841/10813344/8a587f08-7e44-11e5-843f-ace5694778d6.png)

![settings](https://cloud.githubusercontent.com/assets/14918841/10813314/57f202e6-7e44-11e5-9d09-83ff59c2f6cc.png)

![ipad definitions](https://cloud.githubusercontent.com/assets/14918841/10814337/5be0fa68-7e4b-11e5-970e-6c1c4a9d0caf.png)

![ipad settings](https://cloud.githubusercontent.com/assets/14918841/10814340/5fdbd926-7e4b-11e5-83d8-19a8c4579001.png)

**Comment by srkrambo** [comment]
So what happens to the current search button action on right( in iPhone)?  Will clicking this do the search action instead?

**Comment by rakeshak** [comment]
The separate search screen that is in the current version of the app is only a stopgap. Our aim is to bring a search bar at the top of the definitions screen, in which case we won't need a search button.

**Comment by srkrambo** [comment]
Ok. So, In iPad Portrait and iPhone we will need show a list in the same screen with searchbar on top. On selecting an item, just hide the list and load the word in the same screen right?

**Comment by srkrambo** [comment]
And where do we need to show ads? Below the gray navigation bar shown above?

**Comment by rakeshak** [comment]
Yes, search bar at the top in iPad portrait mode and tapping a word in the search list displays its definitions, just like in iPhone. 

The ads shall go below the status bar and above the search bar.

**Comment by srkrambo** [comment]
@rakeshak : The third swipe gesture "Swipe from the right edge to left anywhere on the screen to show settings" won't be possible since the iOS 9 shows the list of other apps by default using this gesture. 

![simulator screen shot 08-nov-2015 11 20 26 am](https://cloud.githubusercontent.com/assets/3715771/11019037/226e2e50-860b-11e5-82f9-ca9cebc12421.png)

**Comment by srkrambo** [comment]
@rakeshak : I just checked through some of the slide over libraries and the sliding from right seems to work. So, I will try implementing them.

**Comment by srkrambo** [comment]
@rakeshak  Need this powered by icon for night mode. 
![logo-tiny 3x](https://cloud.githubusercontent.com/assets/3715771/11028707/01af787c-86e7-11e5-99ba-9417983a4e54.png)

**Comment by srkrambo** [comment]
@rakeshak @hcatlin I also need UI/Content for Tips in settings. And email address for Feedback.

**Comment by srkrambo** [comment]
This is done.

**Comment by srkrambo** [comment]
Using "contact@wordset.org" as feedback email address.
