### ISSUE TITLE
should be more obvious that a new word is being added

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#164]
maybe a banner of some sort that stands out?

Here's an example. We can see that all of the text is green. This indicates it is a new word. But it requires a moment of thought. 

<img width="627" alt="screen shot 2015-11-02 at 9 38 32 am" src="https://cloud.githubusercontent.com/assets/4720348/10886004/c33d5a10-8145-11e5-835f-2dd61fa4e90f.png">

**Comment by malrase** [comment]
Is this more obvious in the new design?
https://beta.wordset.org/en/proposals/5659fe01f5d04b0085005809
