### ISSUE TITLE
When alt-spellings go wrong

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#172]
For example, chi and khi are alt spellings of the Greek letter. But if we merge them "chi" -- as in "the circulating life energy that in Chinese philosophy is thought to be inherent in all things" also gets an alt spelling of khi, which is wrong.

**Comment by HamptonMakes** [comment]
Those aren't intended to be merged. That's a synonym, if anything. If every meaning doesn't match, then it is not a simple alt spelling and it's not on the same wordeset.
