### ISSUE TITLE
Chat triangle looks clickable, isn't

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#191]
<img width="181" alt="screen shot 2015-12-09 at 11 25 08 am" src="https://cloud.githubusercontent.com/assets/4720348/11692919/ab338040-9e67-11e5-88c4-a1d159c35e1c.png">

**Comment by interestinall** [comment]
Also, i think the red dot would look better a couple pixels to the right maybe. What do you think?

**Comment by malrase** [comment]
That's actually a triangle for the profile dropdown – it should be clickable?
