### ISSUE TITLE
When chat is active, more dropdown doesn't drop down

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#193]
<img width="554" alt="screen shot 2015-12-10 at 8 42 14 am" src="https://cloud.githubusercontent.com/assets/4720348/11718096/f3650fd4-9f19-11e5-9226-7a02ecbe48f5.png">

**Comment by interestinall** [comment]
These triangles don't work sometimes. I took a screen shot of what the console is printing.

<img width="1280" alt="screen shot 2015-12-10 at 12 01 17 pm" src="https://cloud.githubusercontent.com/assets/4720348/11723816/e3e64f66-9f35-11e5-84de-831ff9734d5b.png">

**Comment by malrase** [comment]
Hmm, I'm finding this difficult to replicate. It might be a recent thing we did (maybe??) – I'm going to push a new version and see if it works.

**Comment by malrase** [comment]
Ah-ha, looks like it's a turbolinks issue.
