### ISSUE TITLE
"Get to fixin" email says there are comments, but there are no comments

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#196]
<img width="679" alt="screen shot 2015-12-10 at 9 56 38 am" src="https://cloud.githubusercontent.com/assets/4720348/11720350/6c9cb9f6-9f24-11e5-8063-51083ade3f68.png">

**Comment by HamptonMakes** [comment]
This email says there are no comments.... ? I'm confused by this issue. It says zero comments. Are you saying we should hide the number of comments?

**Comment by interestinall** [comment]
in the email it says that almost all of them have comments, but none of them do.

**Comment by HamptonMakes** [comment]
Ahhhhhhh.... gotcha! I'll assign this one to you, you can go change the mailer. ;)
