### ISSUE TITLE
Adding labels: when you add a label you shouldn't have to hit "add label" to hide ad label screen

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#202]
Maybe we do a hover map? or clicking anywhere outside the box closes it?

**Comment by malrase** [comment]
The issue here is that a hover is difficult in terms of accessibility – larger hover maps are tricky to navigate onto.
Also, I'd rather not mask the entire page when the dropdown is selected, it seems like stopping people clicking anywhere else is a pain.

**Comment by interestinall** [comment]
maybe we can change the wording when it pops out to "close window" or similar then?
