### ISSUE TITLE
We should add the potential points to finished proposals.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#203]

**Comment by malrase** [comment]
![screen shot 2015-12-11 at 9 50 32am](https://cloud.githubusercontent.com/assets/108884/11751166/a374e30e-9fec-11e5-84dc-88f1de537ed3.png)

This should already be there?

**Comment by interestinall** [comment]
just noticed that this does exist, it is just not very prominent. maybe we should change the color so it pops out a bit more?

**Comment by malrase** [comment]
![screen shot 2015-12-11 at 10 16 15am](https://cloud.githubusercontent.com/assets/108884/11751746/3c421130-9ff0-11e5-866a-d3d149eb29ac.png)

I changed it to be like this. Seems more prominent!
