### ISSUE TITLE
We are getting lots of sign ups, but no one has been added to the email list.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#204]
Not sure if there is a bug somewhere or if every new person is clicking "no."

**Comment by malrase** [comment]
![screen shot 2015-12-11 at 2 17 39pm](https://cloud.githubusercontent.com/assets/108884/11756910/f49fbed2-a011-11e5-8b78-e9931a7c4f41.png)

This is now checked by default. Let's see if that fixes it. If not, we'll look into it as a bug.
