### ISSUE TITLE
Diff markup is problematic in the new design

### ISSUE THREAD

**Issue by sabreuse** [wordset/wordset#213]
In this screenshot, the proposed change at the beginning of the sentence consisted ONLY of the capitalization of the first letter. In the previous site design, diffs behaved as I would expect: the added letter indicated in green and the replaced one struck through and in red. The regex that's being used now is far more greedy and seems to want to add and remove random letters in multiple words.

![screen shot 2015-12-14 at 8 53 06 pm](https://cloud.githubusercontent.com/assets/133336/11799773/fc3e2a1c-a2a4-11e5-9b56-c144ea84e561.png)

**Comment by HamptonMakes** [comment]
Good catch... let me see what I can figure out.
