### ISSUE TITLE
Clicking link in search (instead of hitting enter) doesn't work

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#217]

**Comment by malrase** [comment]
![screen shot 2015-12-15 at 10 39 54am](https://cloud.githubusercontent.com/assets/108884/11820227/3c01b13c-a318-11e5-9015-896fe3ccaba4.png)
Like clicking one of these? It seems to work fine for me?

**Comment by interestinall** [comment]
Yup. Those don't work at all for me. In the bottom left the right address
shows in chrome, but the browser doesn't actually go there.

**Comment by interestinall** [comment]
also doesn't work on ff and safari.

**Comment by malrase** [comment]
Hm. Does the network tab of the inspector say anything?

**Comment by HamptonMakes** [comment]
Definitely is a bug. One I've just fixed... deployment pending.

The issue is that the "blur" event happens on the text field, dismissing the results, faster than the click happens on the link.

Now, we wait 500ms before the blur removes the results.

**Comment by interestinall** [comment]
Network tab doesn't do anything when I click the word.
