### ISSUE TITLE
search results not alphabetical

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#218]
<img width="210" alt="screen shot 2015-12-15 at 12 47 44 pm" src="https://cloud.githubusercontent.com/assets/4720348/11820438/2ef775a0-a32a-11e5-803c-e5bcf1875b6a.png">

**Comment by HamptonMakes** [comment]
It's not that they are mis-ordered... it's that it's showing the wrong results.. those are the results for "hot"

**Comment by HamptonMakes** [comment]
I'm unable to duplicate what's above all day... :P
