### ISSUE TITLE
UL styles showing on iOS ad

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#219]
Not sure if they are meant to be there, but if so they should probably be moved to the right a bit to line up better.
<img width="325" alt="screen shot 2015-12-15 at 1 19 46 pm" src="https://cloud.githubusercontent.com/assets/4720348/11821358/b1fa1242-a32e-11e5-8f00-ab0cd58375a8.png">

**Comment by malrase** [comment]
Yup, they are supposed to be there. I'll add a bit of padding
