### ISSUE TITLE
Finished but not voted through proposals seem to always have grey as the color for the POS

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#220]
<img width="387" alt="screen shot 2015-12-15 at 1 49 18 pm" src="https://cloud.githubusercontent.com/assets/4720348/11822134/c0ce147c-a332-11e5-9789-53b14eaa1630.png">

**Comment by malrase** [comment]
That's intentional. We want to make sure people focus on the changes, and having the colours for the pos are distracting.
