### ISSUE TITLE
Search: it should be more obvious what word is highlighted

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#224]
Now we just have a difference between black and a slightly lighter grey. Maybe we could do something with the background color, for example inverse things?
<img width="225" alt="screen shot 2015-12-16 at 10 58 23 am" src="https://cloud.githubusercontent.com/assets/4720348/11847618/fb5246ca-a3e3-11e5-9430-69d6d5195d12.png">

**Comment by HamptonMakes** [comment]
Wait, do you mean "highlighted" as in hover state?

**Comment by interestinall** [comment]
yup

**Comment by rakeshak** [comment]
![search results hover](https://cloud.githubusercontent.com/assets/14918841/11890598/f957ee8a-a57b-11e5-9f9f-8ca54c87ca8a.jpg)
- Change the background on hover to our yellow
- Keep the font color at #222
- Remove bottom border

More changes:
Font size of the search input and the search results are at 28px and 24px. Change them to 22px. There is no left padding in the search input. Allow 15px.
The left padding in the search results seems to be at 10px Make it 15px.
Reduce the height of the search box as mentioned in my feedback pdf file. 

How much I want to change these things myself is the CSS—would have saved all these typing and your reading :(
