### ISSUE TITLE
We should add an exception for etc. on defs cannot end w/punctuation

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#230]
<img width="454" alt="screen shot 2015-12-17 at 10 32 33 am" src="https://cloud.githubusercontent.com/assets/4720348/11875281/950d94b6-a4a9-11e5-8c3b-efea23af6411.png">

**Comment by HamptonMakes** [comment]
Why not just say "etc"... it's not that bad style!

**Comment by malrase** [comment]
Or avoid "etc." in definitions?
