### ISSUE TITLE
Digest Emails

### ISSUE THREAD

**Issue by hcatlin** [wordset/wordset#33]
You shouldn't get a barrage of email notifications when something gets closed... we should send one email with them all summed up.

**Comment by hcatlin** [comment]
I think this might need some discussion... do we mix them all up? How is it laid out? What would be ideal?

**Comment by interestinall** [comment]
I think it would be good to mimic the site to create a sense of continuity. Maybe something similar to the "recent activity" section, where each one links back to the site if the person wants to see the details of voting or comments.
