### ISSUE TITLE
Doesn't always auto skip on vote

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#39]
When you vote on a proposal, sometimes it skips to the next, sometimes it gets stuck.

**Comment by malrase** [comment]
I've noticed this and I've been trying to figure out under what conditions, more specifically, this happens. It seems utterly random to me. Don't suppose you've noticed a pattern at all?

**Comment by interestinall** [comment]
I think I may have found the culprit. A pusher error. What do you think?

![screen shot 2015-05-19 at 16 07 10](https://cloud.githubusercontent.com/assets/4720348/7704889/5110b3ec-fe41-11e4-83da-d8c6164a7c7f.png)

**Comment by interestinall** [comment]
https://pusher.com/docs/pusher_protocol
