### ISSUE TITLE
Search doesn't find word, add word form says it is in the db

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#41]
![screen shot 2015-05-13 at 16 36 31](https://cloud.githubusercontent.com/assets/4720348/7613111/0ceb0d18-f98f-11e4-8805-f3c1c51bcd09.png)

**Comment by interestinall** [comment]
Msingle came across this problem again today with the word "woot"

**Comment by HamptonMakes** [comment]
confirm fixed.
