### ISSUE TITLE
Skip seems to count as a vote

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#42]
So if you skip something and end up back there you have to hit "withdraw"  before you can vote. 
https://www.wordset.org/proposal/55529ab330336210211d0000
![screen shot 2015-05-14 at 10 20 49](https://cloud.githubusercontent.com/assets/4720348/7628413/4029601e-fa23-11e4-8927-040d514621c5.png)

**Comment by malrase** [comment]
Yeah, this was by design. The "skip" button shouldn't count towards your votes but it does assign a "done" state for you with regards to the proposal.
