### ISSUE TITLE
Use ember-cli-rails gem for wordset-ui integration?

### ISSUE THREAD

**Issue by turboMaCk** [wordset/wordset#6]
Hi guys.
I was experimenting with integration of wordset-ui with wordset-api using [ember-cli-rails gem](https://github.com/rwz/ember-cli-rails). Since I don't know your deploy process and production architecture I don't want to send pull request to main repository (at least without any discussion) but you should test it if you're interested in [my fork](https://github.com/turboMaCk/wordset-api/tree/feature/ember-cli-integration).

**Comment by hcatlin** [comment]
Not sure if we want this full level of integration. Like, we deploy the ui separately. Though, I hate having two separate repos, I'm not sure if I even want to keep with Rails at all (instead of just pulling out Grape and making that work alone).

**Comment by turboMaCk** [comment]
Convention in using ember-cli-rails is to have Ember apps as submodule of Rails repo. Because of this it is not problem to switch backend lately since you have other up to date repo with frontend.

**I'm  using this integration gem on one production and I'm pretty fan of it because:**
* I can deploy fullstack app with Capistrano (yes I had to modify git task in Capistrano 3 to pull submodules and add some NPM, Bower tasks). For example if some breaking chages happend to both api and Client app I can ship them together with one deploy I do not have to care about migrating two things. 
* Rails (Git) track version dependency of Ember app via submodule commits – So it's easy to rollback both to some history state.
* It's really simple to setup new instance full stack app instance.
* You can still use ember separately, proxy it to staging etc.

**Few cons**
* First intialization of fresh deployd app is really CPU intensive task. This is when ember compile happens. and it take some time. 
* It's simply another think which can break.

**Comment by hcatlin** [comment]
Eh, I think we're going to live this as a totally separate thing. We really want to re-use the API with different clients... so probably a better idea.
