### ISSUE TITLE
Search should be able to find a word if the user captializes it.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#62]
If a user types in "Swim" they will get "word doesn't exist" although "swim" is in there. 

This is especially annoying on mobile because cellphones often automatically cap the first word.

**Comment by malrase** [comment]
I added an "autocapitalize='off'" to the search bar, which should kinda-help with the mobile. However it doesn't solve the underlying issue.

**Comment by malrase** [comment]
I was also wondering – are there more than a handful of examples where you *do* want the capitalised version? E.g. Polish is different from polish. 

Just found a new word! Capitonym: https://en.wikipedia.org/wiki/Capitonym

**Comment by interestinall** [comment]
luxfactaest
I also notice in the search, it's case sensitive and doesn't trim leading or trailing spaces when comparing

luxfactaest
So if I could suggest to the application architect some kind of toLowerCase on the back end and trimming spaces
4 minutes ago
