### ISSUE TITLE
Not able to reach the end of proposals

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#70]
Skip or vote reloads the same last proposal.

**Comment by malrase** [comment]
So I don't know if this is "fixed", but as per issue #65, we wanted to redirect to skipped proposals before saying you're finished and redirecting to the end of proposals.

Could that be what you're seeing here?

**Comment by HamptonMakes** [comment]
I _think_ we rewrote this system, so I _think_ it's fixed.
