### ISSUE TITLE
When you make a proposal and it is commented on, clicking on the activity feed link yields a former uncommented state.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#77]

**Comment by interestinall** [comment]
Links in the alert menu work properly.

**Comment by malrase** [comment]
I can't seem to replicate this :(

**Comment by zellerpress** [comment]
I was just able to replicate this. Clicked on a proposal under "Recent Activity" and it took me to the unedited version instead of newest.

**Comment by HamptonMakes** [comment]
I'm 99% we fixed this already (via two methods!)
