### ISSUE TITLE
User should be able to see potential points before they submit proposal.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset#86]

**Comment by malrase** [comment]
This is tricky – because all the "calculate points" logic is done on the Rails API.

We'd have to re-implement all of that on the Ember side, which would be pretty labour-intensive for the browser, I think. Calculating Levenshtein distance would be difficult.

**Comment by interestinall** [comment]
Would it be possible if it was not "live" but worked on a button press?

Maybe that would be dumb.
