### ISSUE TITLE
null part of speech

### ISSUE THREAD

**Issue by msingle** [wordset/wordset#92]
I created a new def for cemetery. I created it with an adj, but the proposal showed as null. I edited the proposal, it showed as adj, I saved again, but the proposal still displayed as null.
I saved it as adv (which it showed correctly), and then saved it as adv, and now it shows correctly

**Comment by interestinall** [comment]
https://www.wordset.org/proposal/55da61de313338008a080000

**Comment by interestinall** [comment]
bryanedu just found another instance of this.
